packages:
  - 'apps/*'
  - 'packages/*'
  - 'tests'
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.116.0'
  - '@supabase/functions-js@2.116.0'
  - '@supabase/postgrest-js@2.116.0'
  - '@supabase/realtime-js@2.116.0'
  - '@supabase/ssr@0.12.7'
  - '@supabase/storage-js@2.116.0'
  - '@supabase/supabase-js@2.116.0'
  - '@typescript-eslint/eslint-plugin@8.70.0'
  - '@typescript-eslint/parser@8.70.0'
  - '@typescript-eslint/project-service@8.70.0'
  - '@typescript-eslint/scope-manager@8.70.0'
  - '@typescript-eslint/tsconfig-utils@8.70.0'
  - '@typescript-eslint/type-utils@8.70.0'
  - '@typescript-eslint/types@8.70.0'
  - '@typescript-eslint/typescript-estree@8.70.0'
  - '@typescript-eslint/utils@8.70.0'
  - '@typescript-eslint/visitor-keys@8.70.0'
  - typescript-eslint@8.70.0
