/**
 * Icons, re-exported so the app takes them through the design system: one icon library, one
 * version, one stroke weight, rather than each app depending on it separately.
 */
export {
  Activity,
  ArrowLeftRight,
  Boxes,
  Building2,
  Calculator,
  ChartColumn,
  CircleCheck,
  Circle,
  CreditCard,
  Download,
  Ellipsis,
  FileText,
  LayoutDashboard,
  MonitorSmartphone,
  ImagePlus,
  Package,
  PackagePlus,
  Receipt,
  Settings,
  ShieldAlert,
  ShoppingCart,
  Store,
  Truck,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';
