/**
 * Types generated from Carl's migrations.
 *
 * GENERATED FILE — do not edit by hand. Regenerate with `pnpm db:types`.
 *
 * Produced by introspecting the real migrations applied to an in-process PostgreSQL, so it
 * needs no Docker and stays correct in CI. See scripts/generate-db-types.mjs.
 *
 * 51 relations, 27 enums, 4 functions.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: string;
          tenant_id: string | null;
          branch_id: string | null;
          actor_id: string | null;
          actor_email: string | null;
          actor_name: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          before_state: Json | null;
          after_state: Json | null;
          metadata: Json;
          device_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          request_id: string | null;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_email?: string | null;
          actor_name?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          metadata?: Json;
          device_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          occurred_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_email?: string | null;
          actor_name?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          metadata?: Json;
          device_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          occurred_at?: string;
        };
        Relationships: [];
      };
      branches: {
        Row: {
          id: string;
          tenant_id: string;
          code: string;
          name: string;
          address: string | null;
          phone: string | null;
          timezone: string | null;
          is_default: boolean;
          is_active: boolean;
          allow_negative_stock: boolean;
          opened_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          code: string;
          name: string;
          address?: string | null;
          phone?: string | null;
          timezone?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          allow_negative_stock?: boolean;
          opened_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          code?: string;
          name?: string;
          address?: string | null;
          phone?: string | null;
          timezone?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          allow_negative_stock?: boolean;
          opened_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cash_movements: {
        Row: {
          id: string;
          session_id: string;
          tenant_id: string;
          branch_id: string;
          movement_type: Database['public']['Enums']['cash_movement_type'];
          amount: number;
          reason: string;
          notes: string | null;
          performed_by: string;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          tenant_id: string;
          branch_id: string;
          movement_type: Database['public']['Enums']['cash_movement_type'];
          amount: number;
          reason: string;
          notes?: string | null;
          performed_by: string;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          tenant_id?: string;
          branch_id?: string;
          movement_type?: Database['public']['Enums']['cash_movement_type'];
          amount?: number;
          reason?: string;
          notes?: string | null;
          performed_by?: string;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      cash_registers: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cash_sessions: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          register_id: string;
          device_id: string | null;
          status: Database['public']['Enums']['cash_session_status'];
          opening_float: number;
          cash_sales: number;
          cash_refunds: number;
          cash_in: number;
          cash_out: number;
          cash_expenses: number;
          expected_cash: number | null;
          counted_cash: number | null;
          variance: number | null;
          variance_note: string | null;
          opened_by: string;
          opened_at: string;
          closed_by: string | null;
          closed_at: string | null;
          reconciled_by: string | null;
          reconciled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          register_id: string;
          device_id?: string | null;
          status?: Database['public']['Enums']['cash_session_status'];
          opening_float?: number;
          cash_sales?: number;
          cash_refunds?: number;
          cash_in?: number;
          cash_out?: number;
          cash_expenses?: number;
          expected_cash?: number | null;
          counted_cash?: number | null;
          variance?: number | null;
          variance_note?: string | null;
          opened_by: string;
          opened_at?: string;
          closed_by?: string | null;
          closed_at?: string | null;
          reconciled_by?: string | null;
          reconciled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          register_id?: string;
          device_id?: string | null;
          status?: Database['public']['Enums']['cash_session_status'];
          opening_float?: number;
          cash_sales?: number;
          cash_refunds?: number;
          cash_in?: number;
          cash_out?: number;
          cash_expenses?: number;
          expected_cash?: number | null;
          counted_cash?: number | null;
          variance?: number | null;
          variance_note?: string | null;
          opened_by?: string;
          opened_at?: string;
          closed_by?: string | null;
          closed_at?: string | null;
          reconciled_by?: string | null;
          reconciled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          tenant_id: string;
          parent_id: string | null;
          name: string;
          description: string | null;
          colour: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          parent_id?: string | null;
          name: string;
          description?: string | null;
          colour?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          parent_id?: string | null;
          name?: string;
          description?: string | null;
          colour?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          notes: string | null;
          default_tier: Database['public']['Enums']['price_tier'];
          balance: number;
          credit_limit: number;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          notes?: string | null;
          default_tier?: Database['public']['Enums']['price_tier'];
          balance?: number;
          credit_limit?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          notes?: string | null;
          default_tier?: Database['public']['Enums']['price_tier'];
          balance?: number;
          credit_limit?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      device_activations: {
        Row: {
          id: string;
          tenant_id: string;
          device_id: string;
          code_hash: string;
          code_hint: string;
          expires_at: string;
          max_attempts: number;
          attempt_count: number;
          consumed_at: string | null;
          consumed_by: string | null;
          consumed_ip: string | null;
          revoked_at: string | null;
          revoked_by: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          device_id: string;
          code_hash: string;
          code_hint: string;
          expires_at: string;
          max_attempts?: number;
          attempt_count?: number;
          consumed_at?: string | null;
          consumed_by?: string | null;
          consumed_ip?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          device_id?: string;
          code_hash?: string;
          code_hint?: string;
          expires_at?: string;
          max_attempts?: number;
          attempt_count?: number;
          consumed_at?: string | null;
          consumed_by?: string | null;
          consumed_ip?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      device_sessions: {
        Row: {
          id: string;
          device_id: string;
          tenant_id: string;
          secret_hash: string;
          install_id: string;
          last_seen_at: string;
          expires_at: string;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          device_id: string;
          tenant_id: string;
          secret_hash: string;
          install_id: string;
          last_seen_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          device_id?: string;
          tenant_id?: string;
          secret_hash?: string;
          install_id?: string;
          last_seen_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      devices: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          code: string;
          name: string;
          status: Database['public']['Enums']['device_status'];
          platform: Database['public']['Enums']['device_platform'] | null;
          secret_hash: string | null;
          secret_rotated_at: string | null;
          app_version: string | null;
          os_version: string | null;
          last_seen_at: string | null;
          last_sync_at: string | null;
          pending_sync_count: number;
          authorized_until: string | null;
          offline_grace_hours: number;
          activated_at: string | null;
          activated_by: string | null;
          suspended_at: string | null;
          revoked_at: string | null;
          revoked_by: string | null;
          revoked_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          code: string;
          name: string;
          status?: Database['public']['Enums']['device_status'];
          platform?: Database['public']['Enums']['device_platform'] | null;
          secret_hash?: string | null;
          secret_rotated_at?: string | null;
          app_version?: string | null;
          os_version?: string | null;
          last_seen_at?: string | null;
          last_sync_at?: string | null;
          pending_sync_count?: number;
          authorized_until?: string | null;
          offline_grace_hours?: number;
          activated_at?: string | null;
          activated_by?: string | null;
          suspended_at?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          revoked_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          code?: string;
          name?: string;
          status?: Database['public']['Enums']['device_status'];
          platform?: Database['public']['Enums']['device_platform'] | null;
          secret_hash?: string | null;
          secret_rotated_at?: string | null;
          app_version?: string | null;
          os_version?: string | null;
          last_seen_at?: string | null;
          last_sync_at?: string | null;
          pending_sync_count?: number;
          authorized_until?: string | null;
          offline_grace_hours?: number;
          activated_at?: string | null;
          activated_by?: string | null;
          suspended_at?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          revoked_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expense_categories: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          category_id: string | null;
          reference: string;
          description: string;
          amount: number;
          method: Database['public']['Enums']['payment_method'];
          payment_reference: string | null;
          receipt_url: string | null;
          status: Database['public']['Enums']['expense_status'];
          expense_date: string;
          cash_session_id: string | null;
          created_by: string;
          approved_by: string | null;
          approved_at: string | null;
          rejected_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          category_id?: string | null;
          reference: string;
          description: string;
          amount: number;
          method?: Database['public']['Enums']['payment_method'];
          payment_reference?: string | null;
          receipt_url?: string | null;
          status?: Database['public']['Enums']['expense_status'];
          expense_date?: string;
          cash_session_id?: string | null;
          created_by: string;
          approved_by?: string | null;
          approved_at?: string | null;
          rejected_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          category_id?: string | null;
          reference?: string;
          description?: string;
          amount?: number;
          method?: Database['public']['Enums']['payment_method'];
          payment_reference?: string | null;
          receipt_url?: string | null;
          status?: Database['public']['Enums']['expense_status'];
          expense_date?: string;
          cash_session_id?: string | null;
          created_by?: string;
          approved_by?: string | null;
          approved_at?: string | null;
          rejected_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      idempotency_keys: {
        Row: {
          id: string;
          tenant_id: string;
          key: string;
          operation: string;
          request_fingerprint: string;
          status: Database['public']['Enums']['idempotency_status'];
          result_id: string | null;
          result: Json | null;
          error_code: string | null;
          device_id: string | null;
          user_id: string | null;
          expires_at: string;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key: string;
          operation: string;
          request_fingerprint: string;
          status?: Database['public']['Enums']['idempotency_status'];
          result_id?: string | null;
          result?: Json | null;
          error_code?: string | null;
          device_id?: string | null;
          user_id?: string | null;
          expires_at?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          key?: string;
          operation?: string;
          request_fingerprint?: string;
          status?: Database['public']['Enums']['idempotency_status'];
          result_id?: string | null;
          result?: Json | null;
          error_code?: string | null;
          device_id?: string | null;
          user_id?: string | null;
          expires_at?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      installations: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string | null;
          reference: string;
          status: Database['public']['Enums']['installation_status'];
          scheduled_for: string | null;
          started_at: string | null;
          completed_at: string | null;
          installer_id: string | null;
          installer_name: string | null;
          location: string | null;
          device_count: number;
          configuration: Json;
          notes: string | null;
          signoff_url: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id?: string | null;
          reference: string;
          status?: Database['public']['Enums']['installation_status'];
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          installer_id?: string | null;
          installer_name?: string | null;
          location?: string | null;
          device_count?: number;
          configuration?: Json;
          notes?: string | null;
          signoff_url?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string | null;
          reference?: string;
          status?: Database['public']['Enums']['installation_status'];
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          installer_id?: string | null;
          installer_name?: string | null;
          location?: string | null;
          device_count?: number;
          configuration?: Json;
          notes?: string | null;
          signoff_url?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          quantity: number;
          reserved: number;
          reorder_level: number;
          last_counted_at: string | null;
          last_movement_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          quantity?: number;
          reserved?: number;
          reorder_level?: number;
          last_counted_at?: string | null;
          last_movement_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          product_id?: string;
          quantity?: number;
          reserved?: number;
          reorder_level?: number;
          last_counted_at?: string | null;
          last_movement_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_movements: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          movement_type: Database['public']['Enums']['movement_type'];
          quantity: number;
          balance_after: number;
          unit_cost: number;
          reference_type: string | null;
          reference_id: string | null;
          reason: string | null;
          notes: string | null;
          performed_by: string | null;
          device_id: string | null;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          movement_type: Database['public']['Enums']['movement_type'];
          quantity: number;
          balance_after: number;
          unit_cost?: number;
          reference_type?: string | null;
          reference_id?: string | null;
          reason?: string | null;
          notes?: string | null;
          performed_by?: string | null;
          device_id?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          product_id?: string;
          movement_type?: Database['public']['Enums']['movement_type'];
          quantity?: number;
          balance_after?: number;
          unit_cost?: number;
          reference_type?: string | null;
          reference_id?: string | null;
          reason?: string | null;
          notes?: string | null;
          performed_by?: string | null;
          device_id?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      maintenance_records: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string | null;
          device_id: string | null;
          reference: string;
          status: Database['public']['Enums']['maintenance_status'];
          priority: Database['public']['Enums']['maintenance_priority'];
          issue: string;
          description: string | null;
          resolution: string | null;
          reported_by: string | null;
          reporter_name: string | null;
          technician_id: string | null;
          reported_at: string;
          acknowledged_at: string | null;
          resolved_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id?: string | null;
          device_id?: string | null;
          reference: string;
          status?: Database['public']['Enums']['maintenance_status'];
          priority?: Database['public']['Enums']['maintenance_priority'];
          issue: string;
          description?: string | null;
          resolution?: string | null;
          reported_by?: string | null;
          reporter_name?: string | null;
          technician_id?: string | null;
          reported_at?: string;
          acknowledged_at?: string | null;
          resolved_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string | null;
          device_id?: string | null;
          reference?: string;
          status?: Database['public']['Enums']['maintenance_status'];
          priority?: Database['public']['Enums']['maintenance_priority'];
          issue?: string;
          description?: string | null;
          resolution?: string | null;
          reported_by?: string | null;
          reporter_name?: string | null;
          technician_id?: string | null;
          reported_at?: string;
          acknowledged_at?: string | null;
          resolved_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      membership_branches: {
        Row: {
          membership_id: string;
          branch_id: string;
          created_at: string;
        };
        Insert: {
          membership_id: string;
          branch_id: string;
          created_at?: string;
        };
        Update: {
          membership_id?: string;
          branch_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      membership_roles: {
        Row: {
          id: string;
          membership_id: string;
          role_id: string;
          branch_id: string | null;
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          id?: string;
          membership_id: string;
          role_id: string;
          branch_id?: string | null;
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          id?: string;
          membership_id?: string;
          role_id?: string;
          branch_id?: string | null;
          granted_by?: string | null;
          granted_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string | null;
          user_id: string | null;
          kind: string;
          severity: Database['public']['Enums']['notification_severity'];
          title: string;
          body: string | null;
          link: string | null;
          metadata: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id?: string | null;
          user_id?: string | null;
          kind: string;
          severity?: Database['public']['Enums']['notification_severity'];
          title: string;
          body?: string | null;
          link?: string | null;
          metadata?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string | null;
          user_id?: string | null;
          kind?: string;
          severity?: Database['public']['Enums']['notification_severity'];
          title?: string;
          body?: string | null;
          link?: string | null;
          metadata?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          key: string;
          resource: string;
          action: string;
          description: string;
          created_at: string;
        };
        Insert: {
          key: string;
          resource: string;
          action: string;
          description: string;
          created_at?: string;
        };
        Update: {
          key?: string;
          resource?: string;
          action?: string;
          description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      platform_admins: {
        Row: {
          user_id: string;
          granted_by: string | null;
          granted_at: string;
          note: string | null;
        };
        Insert: {
          user_id: string;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          user_id?: string;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      product_barcodes: {
        Row: {
          id: string;
          tenant_id: string;
          product_id: string;
          barcode: string;
          is_primary: boolean;
          pack_size: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          product_id: string;
          barcode: string;
          is_primary?: boolean;
          pack_size?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          product_id?: string;
          barcode?: string;
          is_primary?: boolean;
          pack_size?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      product_prices: {
        Row: {
          id: string;
          tenant_id: string;
          product_id: string;
          branch_id: string | null;
          tier: Database['public']['Enums']['price_tier'];
          amount: number;
          min_quantity: number;
          effective_from: string;
          effective_to: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          product_id: string;
          branch_id?: string | null;
          tier?: Database['public']['Enums']['price_tier'];
          amount: number;
          min_quantity?: number;
          effective_from?: string;
          effective_to?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          product_id?: string;
          branch_id?: string | null;
          tier?: Database['public']['Enums']['price_tier'];
          amount?: number;
          min_quantity?: number;
          effective_from?: string;
          effective_to?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          tenant_id: string;
          category_id: string | null;
          name: string;
          sku: string;
          description: string | null;
          image_url: string | null;
          unit: string;
          allow_fractional: boolean;
          average_cost: number;
          last_cost: number;
          tax_mode: Database['public']['Enums']['tax_mode'];
          tax_rate: number | null;
          min_stock: number;
          reorder_level: number;
          reorder_quantity: number;
          is_active: boolean;
          is_stock_tracked: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          category_id?: string | null;
          name: string;
          sku: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          allow_fractional?: boolean;
          average_cost?: number;
          last_cost?: number;
          tax_mode?: Database['public']['Enums']['tax_mode'];
          tax_rate?: number | null;
          min_stock?: number;
          reorder_level?: number;
          reorder_quantity?: number;
          is_active?: boolean;
          is_stock_tracked?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          category_id?: string | null;
          name?: string;
          sku?: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          allow_fractional?: boolean;
          average_cost?: number;
          last_cost?: number;
          tax_mode?: Database['public']['Enums']['tax_mode'];
          tax_rate?: number | null;
          min_stock?: number;
          reorder_level?: number;
          reorder_quantity?: number;
          is_active?: boolean;
          is_stock_tracked?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      purchase_items: {
        Row: {
          id: string;
          purchase_id: string;
          tenant_id: string;
          product_id: string;
          line_number: number;
          quantity_ordered: number;
          quantity_received: number;
          unit_cost: number;
          discount_amount: number;
          tax_amount: number;
          line_total: number;
          expiry_date: string | null;
          batch_number: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          purchase_id: string;
          tenant_id: string;
          product_id: string;
          line_number: number;
          quantity_ordered: number;
          quantity_received?: number;
          unit_cost: number;
          discount_amount?: number;
          tax_amount?: number;
          line_total: number;
          expiry_date?: string | null;
          batch_number?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          purchase_id?: string;
          tenant_id?: string;
          product_id?: string;
          line_number?: number;
          quantity_ordered?: number;
          quantity_received?: number;
          unit_cost?: number;
          discount_amount?: number;
          tax_amount?: number;
          line_total?: number;
          expiry_date?: string | null;
          batch_number?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      purchase_payments: {
        Row: {
          id: string;
          purchase_id: string;
          tenant_id: string;
          branch_id: string;
          method: Database['public']['Enums']['payment_method'];
          amount: number;
          reference: string | null;
          paid_at: string;
          paid_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          purchase_id: string;
          tenant_id: string;
          branch_id: string;
          method: Database['public']['Enums']['payment_method'];
          amount: number;
          reference?: string | null;
          paid_at?: string;
          paid_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          purchase_id?: string;
          tenant_id?: string;
          branch_id?: string;
          method?: Database['public']['Enums']['payment_method'];
          amount?: number;
          reference?: string | null;
          paid_at?: string;
          paid_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      purchases: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          supplier_id: string | null;
          reference: string;
          supplier_invoice_no: string | null;
          status: Database['public']['Enums']['purchase_status'];
          payment_status: Database['public']['Enums']['payment_status'];
          subtotal: number;
          discount_amount: number;
          tax_amount: number;
          shipping_amount: number;
          total: number;
          amount_paid: number;
          notes: string | null;
          ordered_at: string | null;
          expected_at: string | null;
          received_at: string | null;
          due_at: string | null;
          created_by: string | null;
          received_by: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          supplier_id?: string | null;
          reference: string;
          supplier_invoice_no?: string | null;
          status?: Database['public']['Enums']['purchase_status'];
          payment_status?: Database['public']['Enums']['payment_status'];
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          shipping_amount?: number;
          total?: number;
          amount_paid?: number;
          notes?: string | null;
          ordered_at?: string | null;
          expected_at?: string | null;
          received_at?: string | null;
          due_at?: string | null;
          created_by?: string | null;
          received_by?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          supplier_id?: string | null;
          reference?: string;
          supplier_invoice_no?: string | null;
          status?: Database['public']['Enums']['purchase_status'];
          payment_status?: Database['public']['Enums']['payment_status'];
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          shipping_amount?: number;
          total?: number;
          amount_paid?: number;
          notes?: string | null;
          ordered_at?: string | null;
          expected_at?: string | null;
          received_at?: string | null;
          due_at?: string | null;
          created_by?: string | null;
          received_by?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_key: string;
          granted_at: string;
          granted_by: string | null;
        };
        Insert: {
          role_id: string;
          permission_key: string;
          granted_at?: string;
          granted_by?: string | null;
        };
        Update: {
          role_id?: string;
          permission_key?: string;
          granted_at?: string;
          granted_by?: string | null;
        };
        Relationships: [];
      };
      role_template_permissions: {
        Row: {
          template_key: string;
          permission_key: string;
        };
        Insert: {
          template_key: string;
          permission_key: string;
        };
        Update: {
          template_key?: string;
          permission_key?: string;
        };
        Relationships: [];
      };
      role_templates: {
        Row: {
          key: string;
          name: string;
          description: string;
          rank: number;
          created_at: string;
        };
        Insert: {
          key: string;
          name: string;
          description: string;
          rank: number;
          created_at?: string;
        };
        Update: {
          key?: string;
          name?: string;
          description?: string;
          rank?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          tenant_id: string;
          key: string;
          name: string;
          description: string | null;
          rank: number;
          is_system: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key: string;
          name: string;
          description?: string | null;
          rank?: number;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          rank?: number;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sale_items: {
        Row: {
          id: string;
          sale_id: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          line_number: number;
          product_name: string;
          product_sku: string;
          quantity: number;
          unit_price: number;
          unit_cost: number;
          discount_type: Database['public']['Enums']['discount_type'];
          discount_value: number | null;
          discount_amount: number;
          tax_rate: number;
          tax_amount: number;
          line_total: number;
          quantity_returned: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          tenant_id: string;
          branch_id: string;
          product_id: string;
          line_number: number;
          product_name: string;
          product_sku: string;
          quantity: number;
          unit_price: number;
          unit_cost?: number;
          discount_type?: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          discount_amount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total: number;
          quantity_returned?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          tenant_id?: string;
          branch_id?: string;
          product_id?: string;
          line_number?: number;
          product_name?: string;
          product_sku?: string;
          quantity?: number;
          unit_price?: number;
          unit_cost?: number;
          discount_type?: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          discount_amount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total?: number;
          quantity_returned?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      sale_payments: {
        Row: {
          id: string;
          sale_id: string;
          tenant_id: string;
          branch_id: string;
          method: Database['public']['Enums']['payment_method'];
          amount: number;
          reference: string | null;
          received_at: string;
          received_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          tenant_id: string;
          branch_id: string;
          method: Database['public']['Enums']['payment_method'];
          amount: number;
          reference?: string | null;
          received_at?: string;
          received_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          tenant_id?: string;
          branch_id?: string;
          method?: Database['public']['Enums']['payment_method'];
          amount?: number;
          reference?: string | null;
          received_at?: string;
          received_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sale_return_items: {
        Row: {
          id: string;
          return_id: string;
          sale_item_id: string;
          tenant_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          tax_amount: number;
          line_total: number;
          condition: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          return_id: string;
          sale_item_id: string;
          tenant_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          tax_amount?: number;
          line_total: number;
          condition?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          return_id?: string;
          sale_item_id?: string;
          tenant_id?: string;
          product_id?: string;
          quantity?: number;
          unit_price?: number;
          tax_amount?: number;
          line_total?: number;
          condition?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sale_returns: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          sale_id: string;
          return_number: string;
          reason: string;
          notes: string | null;
          subtotal: number;
          tax_amount: number;
          total: number;
          refund_method: Database['public']['Enums']['payment_method'] | null;
          refund_reference: string | null;
          refunded_amount: number;
          restocked: boolean;
          processed_by: string;
          approved_by: string | null;
          device_id: string | null;
          cash_session_id: string | null;
          returned_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          sale_id: string;
          return_number: string;
          reason: string;
          notes?: string | null;
          subtotal: number;
          tax_amount?: number;
          total: number;
          refund_method?: Database['public']['Enums']['payment_method'] | null;
          refund_reference?: string | null;
          refunded_amount?: number;
          restocked?: boolean;
          processed_by: string;
          approved_by?: string | null;
          device_id?: string | null;
          cash_session_id?: string | null;
          returned_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          sale_id?: string;
          return_number?: string;
          reason?: string;
          notes?: string | null;
          subtotal?: number;
          tax_amount?: number;
          total?: number;
          refund_method?: Database['public']['Enums']['payment_method'] | null;
          refund_reference?: string | null;
          refunded_amount?: number;
          restocked?: boolean;
          processed_by?: string;
          approved_by?: string | null;
          device_id?: string | null;
          cash_session_id?: string | null;
          returned_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      sales: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          sale_number: string;
          status: Database['public']['Enums']['sale_status'];
          channel: Database['public']['Enums']['sale_channel'];
          customer_id: string | null;
          cashier_id: string;
          device_id: string | null;
          cash_session_id: string | null;
          tier: Database['public']['Enums']['price_tier'];
          subtotal: number;
          discount_amount: number;
          tax_amount: number;
          total: number;
          cost_total: number;
          amount_paid: number;
          change_given: number;
          amount_refunded: number;
          discount_type: Database['public']['Enums']['discount_type'];
          discount_value: number | null;
          discount_reason: string | null;
          discount_approved_by: string | null;
          note: string | null;
          sold_at: string;
          synced_at: string | null;
          is_offline_sale: boolean;
          voided_at: string | null;
          voided_by: string | null;
          void_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          sale_number: string;
          status?: Database['public']['Enums']['sale_status'];
          channel?: Database['public']['Enums']['sale_channel'];
          customer_id?: string | null;
          cashier_id: string;
          device_id?: string | null;
          cash_session_id?: string | null;
          tier?: Database['public']['Enums']['price_tier'];
          subtotal: number;
          discount_amount?: number;
          tax_amount?: number;
          total: number;
          cost_total?: number;
          amount_paid?: number;
          change_given?: number;
          amount_refunded?: number;
          discount_type?: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          discount_reason?: string | null;
          discount_approved_by?: string | null;
          note?: string | null;
          sold_at?: string;
          synced_at?: string | null;
          is_offline_sale?: boolean;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          sale_number?: string;
          status?: Database['public']['Enums']['sale_status'];
          channel?: Database['public']['Enums']['sale_channel'];
          customer_id?: string | null;
          cashier_id?: string;
          device_id?: string | null;
          cash_session_id?: string | null;
          tier?: Database['public']['Enums']['price_tier'];
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          total?: number;
          cost_total?: number;
          amount_paid?: number;
          change_given?: number;
          amount_refunded?: number;
          discount_type?: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          discount_reason?: string | null;
          discount_approved_by?: string | null;
          note?: string | null;
          sold_at?: string;
          synced_at?: string | null;
          is_offline_sale?: boolean;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stock_count_items: {
        Row: {
          id: string;
          stock_count_id: string;
          tenant_id: string;
          product_id: string;
          expected_quantity: number;
          counted_quantity: number | null;
          variance: number | null;
          unit_cost: number;
          notes: string | null;
          counted_by: string | null;
          counted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          stock_count_id: string;
          tenant_id: string;
          product_id: string;
          expected_quantity: number;
          counted_quantity?: number | null;
          variance?: number | null;
          unit_cost?: number;
          notes?: string | null;
          counted_by?: string | null;
          counted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          stock_count_id?: string;
          tenant_id?: string;
          product_id?: string;
          expected_quantity?: number;
          counted_quantity?: number | null;
          variance?: number | null;
          unit_cost?: number;
          notes?: string | null;
          counted_by?: string | null;
          counted_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      stock_counts: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string;
          reference: string;
          status: Database['public']['Enums']['stock_count_status'];
          category_id: string | null;
          notes: string | null;
          started_by: string | null;
          started_at: string | null;
          submitted_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id: string;
          reference: string;
          status?: Database['public']['Enums']['stock_count_status'];
          category_id?: string | null;
          notes?: string | null;
          started_by?: string | null;
          started_at?: string | null;
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string;
          reference?: string;
          status?: Database['public']['Enums']['stock_count_status'];
          category_id?: string | null;
          notes?: string | null;
          started_by?: string | null;
          started_at?: string | null;
          submitted_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stock_transfer_items: {
        Row: {
          id: string;
          transfer_id: string;
          tenant_id: string;
          product_id: string;
          quantity_requested: number;
          quantity_sent: number | null;
          quantity_received: number | null;
          unit_cost: number;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          transfer_id: string;
          tenant_id: string;
          product_id: string;
          quantity_requested: number;
          quantity_sent?: number | null;
          quantity_received?: number | null;
          unit_cost?: number;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          transfer_id?: string;
          tenant_id?: string;
          product_id?: string;
          quantity_requested?: number;
          quantity_sent?: number | null;
          quantity_received?: number | null;
          unit_cost?: number;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      stock_transfers: {
        Row: {
          id: string;
          tenant_id: string;
          reference: string;
          from_branch_id: string;
          to_branch_id: string;
          status: Database['public']['Enums']['transfer_status'];
          notes: string | null;
          requested_by: string | null;
          requested_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          dispatched_at: string | null;
          received_by: string | null;
          received_at: string | null;
          cancelled_by: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          reference: string;
          from_branch_id: string;
          to_branch_id: string;
          status?: Database['public']['Enums']['transfer_status'];
          notes?: string | null;
          requested_by?: string | null;
          requested_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          dispatched_at?: string | null;
          received_by?: string | null;
          received_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          reference?: string;
          from_branch_id?: string;
          to_branch_id?: string;
          status?: Database['public']['Enums']['transfer_status'];
          notes?: string | null;
          requested_by?: string | null;
          requested_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          dispatched_at?: string | null;
          received_by?: string | null;
          received_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_payments: {
        Row: {
          id: string;
          subscription_id: string;
          tenant_id: string;
          amount: number;
          currency_code: string;
          method: Database['public']['Enums']['payment_method'];
          reference: string | null;
          period_start: string;
          period_end: string;
          paid_at: string;
          recorded_by: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          subscription_id: string;
          tenant_id: string;
          amount: number;
          currency_code?: string;
          method?: Database['public']['Enums']['payment_method'];
          reference?: string | null;
          period_start: string;
          period_end: string;
          paid_at?: string;
          recorded_by: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          subscription_id?: string;
          tenant_id?: string;
          amount?: number;
          currency_code?: string;
          method?: Database['public']['Enums']['payment_method'];
          reference?: string | null;
          period_start?: string;
          period_end?: string;
          paid_at?: string;
          recorded_by?: string;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      subscription_plans: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          price: number;
          currency_code: string;
          interval: Database['public']['Enums']['billing_interval'];
          max_branches: number | null;
          max_devices: number | null;
          max_users: number | null;
          features: Json;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string | null;
          price?: number;
          currency_code?: string;
          interval?: Database['public']['Enums']['billing_interval'];
          max_branches?: number | null;
          max_devices?: number | null;
          max_users?: number | null;
          features?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          price?: number;
          currency_code?: string;
          interval?: Database['public']['Enums']['billing_interval'];
          max_branches?: number | null;
          max_devices?: number | null;
          max_users?: number | null;
          features?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          tenant_id: string;
          plan_id: string;
          status: Database['public']['Enums']['subscription_status'];
          price: number;
          currency_code: string;
          interval: Database['public']['Enums']['billing_interval'];
          current_period_start: string;
          current_period_end: string;
          grace_days: number;
          trial_ends_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          plan_id: string;
          status?: Database['public']['Enums']['subscription_status'];
          price: number;
          currency_code?: string;
          interval?: Database['public']['Enums']['billing_interval'];
          current_period_start?: string;
          current_period_end: string;
          grace_days?: number;
          trial_ends_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          plan_id?: string;
          status?: Database['public']['Enums']['subscription_status'];
          price?: number;
          currency_code?: string;
          interval?: Database['public']['Enums']['billing_interval'];
          current_period_start?: string;
          current_period_end?: string;
          grace_days?: number;
          trial_ends_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          contact_name: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          notes: string | null;
          payment_terms_days: number;
          balance: number;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          notes?: string | null;
          payment_terms_days?: number;
          balance?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          notes?: string | null;
          payment_terms_days?: number;
          balance?: number;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sync_conflicts: {
        Row: {
          id: string;
          tenant_id: string;
          branch_id: string | null;
          device_id: string | null;
          conflict_type: Database['public']['Enums']['sync_conflict_type'];
          status: Database['public']['Enums']['sync_conflict_status'];
          entity_type: string;
          entity_id: string | null;
          payload: Json;
          detail: string;
          resolved_by: string | null;
          resolved_at: string | null;
          resolution_note: string | null;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          branch_id?: string | null;
          device_id?: string | null;
          conflict_type: Database['public']['Enums']['sync_conflict_type'];
          status?: Database['public']['Enums']['sync_conflict_status'];
          entity_type: string;
          entity_id?: string | null;
          payload: Json;
          detail: string;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          branch_id?: string | null;
          device_id?: string | null;
          conflict_type?: Database['public']['Enums']['sync_conflict_type'];
          status?: Database['public']['Enums']['sync_conflict_status'];
          entity_type?: string;
          entity_id?: string | null;
          payload?: Json;
          detail?: string;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      tenant_memberships: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          status: Database['public']['Enums']['membership_status'];
          is_owner: boolean;
          staff_code: string | null;
          job_title: string | null;
          invited_by: string | null;
          invited_at: string;
          accepted_at: string | null;
          suspended_at: string | null;
          removed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          status?: Database['public']['Enums']['membership_status'];
          is_owner?: boolean;
          staff_code?: string | null;
          job_title?: string | null;
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
          suspended_at?: string | null;
          removed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          user_id?: string;
          status?: Database['public']['Enums']['membership_status'];
          is_owner?: boolean;
          staff_code?: string | null;
          job_title?: string | null;
          invited_by?: string | null;
          invited_at?: string;
          accepted_at?: string | null;
          suspended_at?: string | null;
          removed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tenant_support_grants: {
        Row: {
          id: string;
          tenant_id: string;
          grantee_id: string;
          reason: string;
          maintenance_id: string | null;
          allow_write: boolean;
          granted_by: string;
          granted_at: string;
          expires_at: string;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          grantee_id: string;
          reason: string;
          maintenance_id?: string | null;
          allow_write?: boolean;
          granted_by: string;
          granted_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          grantee_id?: string;
          reason?: string;
          maintenance_id?: string | null;
          allow_write?: boolean;
          granted_by?: string;
          granted_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      tenants: {
        Row: {
          id: string;
          slug: string;
          name: string;
          legal_name: string | null;
          status: Database['public']['Enums']['tenant_status'];
          email: string | null;
          phone: string | null;
          address: string | null;
          country_code: string;
          currency_code: string;
          timezone: string;
          logo_url: string | null;
          receipt_footer: string | null;
          tax_registration_no: string | null;
          default_tax_rate: number;
          prices_include_tax: boolean;
          trial_ends_at: string | null;
          suspended_at: string | null;
          suspension_reason: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          legal_name?: string | null;
          status?: Database['public']['Enums']['tenant_status'];
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          country_code?: string;
          currency_code?: string;
          timezone?: string;
          logo_url?: string | null;
          receipt_footer?: string | null;
          tax_registration_no?: string | null;
          default_tax_rate?: number;
          prices_include_tax?: boolean;
          trial_ends_at?: string | null;
          suspended_at?: string | null;
          suspension_reason?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          legal_name?: string | null;
          status?: Database['public']['Enums']['tenant_status'];
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          country_code?: string;
          currency_code?: string;
          timezone?: string;
          logo_url?: string | null;
          receipt_footer?: string | null;
          tax_registration_no?: string | null;
          default_tax_rate?: number;
          prices_include_tax?: boolean;
          trial_ends_at?: string | null;
          suspended_at?: string | null;
          suspension_reason?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      devices_safe: {
        Row: {
          id: string | null;
          tenant_id: string | null;
          branch_id: string | null;
          code: string | null;
          name: string | null;
          status: Database['public']['Enums']['device_status'] | null;
          platform: Database['public']['Enums']['device_platform'] | null;
          app_version: string | null;
          os_version: string | null;
          last_seen_at: string | null;
          last_sync_at: string | null;
          pending_sync_count: number | null;
          authorized_until: string | null;
          offline_grace_hours: number | null;
          activated_at: string | null;
          revoked_at: string | null;
          revoked_reason: string | null;
          created_at: string | null;
          updated_at: string | null;
          health: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      activate_device: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      issue_activation_code: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      provision_tenant: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      revoke_device: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: {
      billing_interval: 'MONTHLY' | 'QUARTERLY' | 'ANNUAL';
      cash_movement_type: 'IN' | 'OUT' | 'DROP' | 'PICKUP';
      cash_session_status: 'OPEN' | 'CLOSED' | 'RECONCILED';
      device_platform: 'WINDOWS' | 'MACOS' | 'LINUX' | 'WEB' | 'ANDROID' | 'IOS';
      device_status: 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'REVOKED';
      discount_type: 'NONE' | 'PERCENTAGE' | 'AMOUNT';
      expense_status: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'PAID';
      idempotency_status: 'IN_PROGRESS' | 'SUCCEEDED' | 'FAILED';
      installation_status: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
      maintenance_priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
      maintenance_status: 'OPEN' | 'IN_PROGRESS' | 'WAITING_CUSTOMER' | 'RESOLVED' | 'CLOSED';
      membership_status: 'INVITED' | 'ACTIVE' | 'SUSPENDED' | 'REMOVED';
      movement_type: 'OPENING_STOCK' | 'PURCHASE' | 'SALE' | 'SALE_RETURN' | 'PURCHASE_RETURN' | 'TRANSFER_OUT' | 'TRANSFER_IN' | 'ADJUSTMENT_IN' | 'ADJUSTMENT_OUT' | 'STOCK_COUNT' | 'DAMAGE' | 'EXPIRED' | 'THEFT' | 'SALE_VOID';
      notification_severity: 'INFO' | 'WARNING' | 'CRITICAL';
      payment_method: 'CASH' | 'MOMO' | 'BANK_TRANSFER' | 'CARD' | 'CREDIT' | 'OTHER';
      payment_status: 'UNPAID' | 'PARTIAL' | 'PAID';
      price_tier: 'RETAIL' | 'WHOLESALE';
      purchase_status: 'DRAFT' | 'ORDERED' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'CANCELLED';
      sale_channel: 'POS' | 'ONLINE' | 'MANUAL';
      sale_status: 'COMPLETED' | 'VOIDED' | 'PARTIALLY_RETURNED' | 'RETURNED';
      stock_count_status: 'DRAFT' | 'IN_PROGRESS' | 'PENDING_APPROVAL' | 'APPROVED' | 'CANCELLED';
      subscription_status: 'TRIALING' | 'ACTIVE' | 'PAST_DUE' | 'SUSPENDED' | 'CANCELLED';
      sync_conflict_status: 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED';
      sync_conflict_type: 'INSUFFICIENT_STOCK' | 'PRICE_CHANGED' | 'PRODUCT_REMOVED' | 'DUPLICATE_TRANSACTION' | 'DEVICE_REVOKED' | 'TENANT_SUSPENDED' | 'VALIDATION_FAILED';
      tax_mode: 'INCLUSIVE' | 'EXCLUSIVE' | 'EXEMPT';
      tenant_status: 'TRIAL' | 'ACTIVE' | 'GRACE_PERIOD' | 'SUSPENDED' | 'CANCELLED';
      transfer_status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
    };
    CompositeTypes: Record<string, never>;
  };
}


export type Tables = Database['public']['Tables'];
export type Views = Database['public']['Views'];
export type Enums = Database['public']['Enums'];

export type Row<T extends keyof Tables> = Tables[T]['Row'];
export type InsertRow<T extends keyof Tables> = Tables[T]['Insert'];
export type UpdateRow<T extends keyof Tables> = Tables[T]['Update'];
export type ViewRow<T extends keyof Views> = Views[T]['Row'];
