-- =============================================================================
-- 0014 · Role template seed
--
-- GENERATED FILE — do not edit by hand.
--
-- Regenerate with:  node scripts/generate-role-templates-migration.mjs
-- Source of truth:  packages/domain/src/access/roles.ts
--
-- provision_tenant() copies these into per-tenant `roles` rows. They are templates: a
-- tenant administrator may then edit the permissions on their own copy, because one
-- business's idea of "cashier" is not another's.
--
-- 8 templates, 218 grants.
-- =============================================================================

create table if not exists role_templates (
  key         app.slug primary key,
  name        app.label not null,
  description text not null,
  rank        smallint not null,
  created_at  timestamptz not null default now(),

  constraint role_templates_rank_range check (rank between 0 and 100)
);

create table if not exists role_template_permissions (
  template_key   text not null references role_templates (key) on delete cascade,
  permission_key text not null references permissions (key) on delete cascade,
  primary key (template_key, permission_key)
);

alter table role_templates enable row level security;
alter table role_templates force row level security;
alter table role_template_permissions enable row level security;
alter table role_template_permissions force row level security;

-- Readable by any signed-in user so the role editor can offer them. Not sensitive: these
-- describe Carl's capabilities, not any business's configuration.
create policy role_templates_select on role_templates
  for select to authenticated using (true);
create policy role_template_permissions_select on role_template_permissions
  for select to authenticated using (true);

insert into role_templates (key, name, description, rank) values
  ('tenant_owner', 'Owner', 'The business owner. Full control of the tenant, including billing and transferring ownership.', 10),
  ('tenant_admin', 'Administrator', 'Full control of the business across every branch.', 20),
  ('branch_manager', 'Branch Manager', 'Runs one or more branches: staff, stock, pricing, refunds and reporting.', 30),
  ('inventory_manager', 'Inventory Manager', 'Manages stock, purchasing and suppliers. No access to sales revenue.', 40),
  ('accountant', 'Accountant', 'Reads financial data across branches. Cannot sell or change stock.', 40),
  ('supervisor', 'Supervisor', 'Runs a shift: approves refunds and discounts, handles the cash drawer.', 50),
  ('cashier', 'Cashier', 'Operates the till. Cannot refund, discount, or view cost prices.', 60),
  ('staff', 'Staff', 'Read-only access to the catalogue and stock levels.', 70)
on conflict (key) do update
  set name = excluded.name, description = excluded.description, rank = excluded.rank;

-- Rewritten wholesale so a permission removed from a template in code is removed here too.
delete from role_template_permissions;

insert into role_template_permissions (template_key, permission_key) values
  ('tenant_owner', 'sales.view'),
  ('tenant_owner', 'sales.view_all'),
  ('tenant_owner', 'sales.create'),
  ('tenant_owner', 'sales.void'),
  ('tenant_owner', 'sales.refund'),
  ('tenant_owner', 'sales.discount'),
  ('tenant_owner', 'sales.discount_unrestricted'),
  ('tenant_owner', 'sales.price_override'),
  ('tenant_owner', 'sales.sell_wholesale'),
  ('tenant_owner', 'products.view'),
  ('tenant_owner', 'products.create'),
  ('tenant_owner', 'products.update'),
  ('tenant_owner', 'products.delete'),
  ('tenant_owner', 'products.view_cost'),
  ('tenant_owner', 'products.manage_pricing'),
  ('tenant_owner', 'categories.manage'),
  ('tenant_owner', 'inventory.view'),
  ('tenant_owner', 'inventory.adjust'),
  ('tenant_owner', 'inventory.transfer_create'),
  ('tenant_owner', 'inventory.transfer_approve'),
  ('tenant_owner', 'inventory.transfer_receive'),
  ('tenant_owner', 'inventory.count_create'),
  ('tenant_owner', 'inventory.count_approve'),
  ('tenant_owner', 'purchases.view'),
  ('tenant_owner', 'purchases.create'),
  ('tenant_owner', 'purchases.receive'),
  ('tenant_owner', 'purchases.delete'),
  ('tenant_owner', 'suppliers.view'),
  ('tenant_owner', 'suppliers.manage'),
  ('tenant_owner', 'customers.view'),
  ('tenant_owner', 'customers.create'),
  ('tenant_owner', 'customers.update'),
  ('tenant_owner', 'customers.delete'),
  ('tenant_owner', 'expenses.view'),
  ('tenant_owner', 'expenses.create'),
  ('tenant_owner', 'expenses.approve'),
  ('tenant_owner', 'register.open'),
  ('tenant_owner', 'register.close'),
  ('tenant_owner', 'register.cash_movement'),
  ('tenant_owner', 'register.view_variance'),
  ('tenant_owner', 'reports.view'),
  ('tenant_owner', 'reports.view_financial'),
  ('tenant_owner', 'reports.view_all_branches'),
  ('tenant_owner', 'reports.export'),
  ('tenant_owner', 'branches.view'),
  ('tenant_owner', 'branches.manage'),
  ('tenant_owner', 'staff.view'),
  ('tenant_owner', 'staff.manage'),
  ('tenant_owner', 'roles.manage'),
  ('tenant_owner', 'settings.view'),
  ('tenant_owner', 'settings.manage'),
  ('tenant_owner', 'devices.view'),
  ('tenant_owner', 'devices.manage'),
  ('tenant_owner', 'audit.view'),
  ('tenant_admin', 'sales.view'),
  ('tenant_admin', 'sales.view_all'),
  ('tenant_admin', 'sales.create'),
  ('tenant_admin', 'sales.void'),
  ('tenant_admin', 'sales.refund'),
  ('tenant_admin', 'sales.discount'),
  ('tenant_admin', 'sales.discount_unrestricted'),
  ('tenant_admin', 'sales.price_override'),
  ('tenant_admin', 'sales.sell_wholesale'),
  ('tenant_admin', 'products.view'),
  ('tenant_admin', 'products.create'),
  ('tenant_admin', 'products.update'),
  ('tenant_admin', 'products.delete'),
  ('tenant_admin', 'products.view_cost'),
  ('tenant_admin', 'products.manage_pricing'),
  ('tenant_admin', 'categories.manage'),
  ('tenant_admin', 'inventory.view'),
  ('tenant_admin', 'inventory.adjust'),
  ('tenant_admin', 'inventory.transfer_create'),
  ('tenant_admin', 'inventory.transfer_approve'),
  ('tenant_admin', 'inventory.transfer_receive'),
  ('tenant_admin', 'inventory.count_create'),
  ('tenant_admin', 'inventory.count_approve'),
  ('tenant_admin', 'purchases.view'),
  ('tenant_admin', 'purchases.create'),
  ('tenant_admin', 'purchases.receive'),
  ('tenant_admin', 'purchases.delete'),
  ('tenant_admin', 'suppliers.view'),
  ('tenant_admin', 'suppliers.manage'),
  ('tenant_admin', 'customers.view'),
  ('tenant_admin', 'customers.create'),
  ('tenant_admin', 'customers.update'),
  ('tenant_admin', 'customers.delete'),
  ('tenant_admin', 'expenses.view'),
  ('tenant_admin', 'expenses.create'),
  ('tenant_admin', 'expenses.approve'),
  ('tenant_admin', 'register.open'),
  ('tenant_admin', 'register.close'),
  ('tenant_admin', 'register.cash_movement'),
  ('tenant_admin', 'register.view_variance'),
  ('tenant_admin', 'reports.view'),
  ('tenant_admin', 'reports.view_financial'),
  ('tenant_admin', 'reports.view_all_branches'),
  ('tenant_admin', 'reports.export'),
  ('tenant_admin', 'branches.view'),
  ('tenant_admin', 'branches.manage'),
  ('tenant_admin', 'staff.view'),
  ('tenant_admin', 'staff.manage'),
  ('tenant_admin', 'roles.manage'),
  ('tenant_admin', 'settings.view'),
  ('tenant_admin', 'settings.manage'),
  ('tenant_admin', 'devices.view'),
  ('tenant_admin', 'devices.manage'),
  ('tenant_admin', 'audit.view'),
  ('branch_manager', 'sales.view'),
  ('branch_manager', 'sales.create'),
  ('branch_manager', 'products.view'),
  ('branch_manager', 'inventory.view'),
  ('branch_manager', 'customers.view'),
  ('branch_manager', 'customers.create'),
  ('branch_manager', 'register.open'),
  ('branch_manager', 'register.close'),
  ('branch_manager', 'sales.view_all'),
  ('branch_manager', 'sales.void'),
  ('branch_manager', 'sales.refund'),
  ('branch_manager', 'sales.discount'),
  ('branch_manager', 'sales.sell_wholesale'),
  ('branch_manager', 'customers.update'),
  ('branch_manager', 'register.cash_movement'),
  ('branch_manager', 'register.view_variance'),
  ('branch_manager', 'expenses.view'),
  ('branch_manager', 'expenses.create'),
  ('branch_manager', 'reports.view'),
  ('branch_manager', 'staff.view'),
  ('branch_manager', 'products.create'),
  ('branch_manager', 'products.update'),
  ('branch_manager', 'products.view_cost'),
  ('branch_manager', 'categories.manage'),
  ('branch_manager', 'inventory.adjust'),
  ('branch_manager', 'inventory.transfer_create'),
  ('branch_manager', 'inventory.transfer_approve'),
  ('branch_manager', 'inventory.transfer_receive'),
  ('branch_manager', 'inventory.count_create'),
  ('branch_manager', 'inventory.count_approve'),
  ('branch_manager', 'purchases.view'),
  ('branch_manager', 'purchases.create'),
  ('branch_manager', 'purchases.receive'),
  ('branch_manager', 'suppliers.view'),
  ('branch_manager', 'suppliers.manage'),
  ('branch_manager', 'sales.discount_unrestricted'),
  ('branch_manager', 'sales.price_override'),
  ('branch_manager', 'products.manage_pricing'),
  ('branch_manager', 'expenses.approve'),
  ('branch_manager', 'reports.view_financial'),
  ('branch_manager', 'reports.export'),
  ('branch_manager', 'staff.manage'),
  ('branch_manager', 'devices.view'),
  ('branch_manager', 'branches.view'),
  ('branch_manager', 'settings.view'),
  ('inventory_manager', 'products.view'),
  ('inventory_manager', 'products.create'),
  ('inventory_manager', 'products.update'),
  ('inventory_manager', 'products.view_cost'),
  ('inventory_manager', 'categories.manage'),
  ('inventory_manager', 'inventory.view'),
  ('inventory_manager', 'inventory.adjust'),
  ('inventory_manager', 'inventory.transfer_create'),
  ('inventory_manager', 'inventory.transfer_approve'),
  ('inventory_manager', 'inventory.transfer_receive'),
  ('inventory_manager', 'inventory.count_create'),
  ('inventory_manager', 'inventory.count_approve'),
  ('inventory_manager', 'purchases.view'),
  ('inventory_manager', 'purchases.create'),
  ('inventory_manager', 'purchases.receive'),
  ('inventory_manager', 'suppliers.view'),
  ('inventory_manager', 'suppliers.manage'),
  ('inventory_manager', 'reports.view'),
  ('accountant', 'sales.view'),
  ('accountant', 'sales.view_all'),
  ('accountant', 'products.view'),
  ('accountant', 'products.view_cost'),
  ('accountant', 'inventory.view'),
  ('accountant', 'purchases.view'),
  ('accountant', 'suppliers.view'),
  ('accountant', 'customers.view'),
  ('accountant', 'expenses.view'),
  ('accountant', 'expenses.create'),
  ('accountant', 'expenses.approve'),
  ('accountant', 'register.view_variance'),
  ('accountant', 'reports.view'),
  ('accountant', 'reports.view_financial'),
  ('accountant', 'reports.view_all_branches'),
  ('accountant', 'reports.export'),
  ('accountant', 'audit.view'),
  ('supervisor', 'sales.view'),
  ('supervisor', 'sales.create'),
  ('supervisor', 'products.view'),
  ('supervisor', 'inventory.view'),
  ('supervisor', 'customers.view'),
  ('supervisor', 'customers.create'),
  ('supervisor', 'register.open'),
  ('supervisor', 'register.close'),
  ('supervisor', 'sales.view_all'),
  ('supervisor', 'sales.void'),
  ('supervisor', 'sales.refund'),
  ('supervisor', 'sales.discount'),
  ('supervisor', 'sales.sell_wholesale'),
  ('supervisor', 'customers.update'),
  ('supervisor', 'register.cash_movement'),
  ('supervisor', 'register.view_variance'),
  ('supervisor', 'expenses.view'),
  ('supervisor', 'expenses.create'),
  ('supervisor', 'reports.view'),
  ('supervisor', 'staff.view'),
  ('cashier', 'sales.view'),
  ('cashier', 'sales.create'),
  ('cashier', 'products.view'),
  ('cashier', 'inventory.view'),
  ('cashier', 'customers.view'),
  ('cashier', 'customers.create'),
  ('cashier', 'register.open'),
  ('cashier', 'register.close'),
  ('staff', 'products.view'),
  ('staff', 'inventory.view')
on conflict do nothing;
